### ISSUE TITLE
Tank not moving after going a little distance

### ISSUE THREAD

**Issue by LuciferZ25** [SmashPhil/Vehicles#21]
Edit: It only happens after firing some shells. After I fire say 10 shells from the tank. Hence, the car never stops. But the tank does. 
Hey I'm using the 1.1 version. I spawn a tank in dev mode. I load all the crew. Then I draft the tank. It moves. It fires. Everything is good forawhile. Then the debug screen goes all red and then the tank doesn't move. It fires very well though. It's full tank obviously in dev mode.

**Comment by SmashPhil** [comment]
1. Please include a hugslog link, otherwise there's no way for me to debug it.
2. Easier if you report this on discord, which is where the beta was announced to begin with so either you _can_ post it there or you're just grabbing these prereleases without first stopping by the discord. 

That being said, there have been quite a few changes in the last week or so that have not been pushed and there has been some extensive testing so it's possible you've encountered a mod conflict, or it's just outdated code. No way for me to help without the error log
