### ISSUE TITLE
Projectile damages entities without exploding.

### ISSUE THREAD

**Issue by CodeCado** [SmashPhil/Vehicles#38]
A projectile fired from a tank will damage every pawn without exploding if the target is not that pawn.

Here I target the tile behind the pawn, not the pawn itself.

![imagen](https://user-images.githubusercontent.com/77220489/105530233-4375b680-5cc6-11eb-8322-285ae7c71667.png)

When shooting the tank, if aimed correctly, the pawn will die but the bullet will keep its trajectory.

![imagen](https://user-images.githubusercontent.com/77220489/105530394-7f108080-5cc6-11eb-98bd-2b6d79ec1816.png)

![imagen](https://user-images.githubusercontent.com/77220489/105530758-01994000-5cc7-11eb-9995-8f73a2402bdb.png)

Only explodes if it hits a wall or the cannon is directly aimed at a pawn.

![imagen](https://user-images.githubusercontent.com/77220489/105531031-7a989780-5cc7-11eb-85c9-4b2ce57a736f.png)

**Comment by SmashPhil** [comment]
This is intentional and was just to test how it looked and functioned ingame. I was playing around with the idea of tanks not being a super OP mortar where you could target any cell and explode it directly, but rather had to strategically target solid objects. I wouldn't count on this being in the final release, but as far as the beta is concerned this isn't a bug.

**Comment by CodeCado** [comment]
Well, just saying that the bullet, if it hits, just deals explosive damage to some bodyparts. That centipede needs some direct hits to die, but if you do it that way you can one-shot it because the projectile itself deals like 200-400 damage instead.
