### ISSUE TITLE
Aerial vehicles can't land on colony.

### ISSUE THREAD

**Issue by T-rexsuper1** [SmashPhil/Vehicles#41]
**Describe the bug**
Can't land. 
**To Reproduce**
1. Fly away from colony.
2. Double click the colony.
3. Try to select landing spot, nothing happens.

**Comment by T-rexsuper1** [comment]
![Screenshot_1016](https://user-images.githubusercontent.com/30936470/105666270-2ebd3c80-5ed9-11eb-9a7a-246245dddc63.png)
Clickin', yet I can't land.

**Comment by T-rexsuper1** [comment]
![Screenshot_1017](https://user-images.githubusercontent.com/30936470/105666300-3f6db280-5ed9-11eb-88c6-02db50ee294a.png)
Neither do work.

**Comment by SmashPhil** [comment]
I need logs if you want me to fix the issue.

**Comment by T-rexsuper1** [comment]
Here you go, friend. https://gist.github.com/3542d47aacd93226a9276f3d635896d4

**Comment by T-rexsuper1** [comment]
![Screenshot_1018](https://user-images.githubusercontent.com/30936470/105666471-9b383b80-5ed9-11eb-94aa-0e5bc3c2942c.png)
This when trynna land. Only one (Sparrow) is selected. Was not attacked at any point.

**Comment by SmashPhil** [comment]
Please do not use the master branch for testing. There is a steam workshop page (albeit unlisted) for the closed beta. This is because I'm frequently pushing new stuff that I still need to test, or sending another version over to someone to test independently before pushing it out to the beta. This is one such change (which is still WIP hence why you're getting an error). Thanks

**Comment by SmashPhil** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2356577528

**Comment by T-rexsuper1** [comment]
Sorry my bad
